/*CREATE USERS TABLE*/
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    userName VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);


/*CREATE FORMS TABLE*/
CREATE TABLE forms(
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    is_published BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER REFERENCES users(id)
);

/*CREATE QUESTIONS TABLE*/
CREATE TABLE questions(
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    require BOOLEAN NOT NULL,
    form_id INTEGER REFERENCES forms(id)
);


